name = "najortkr"
main = "_worker.js"
compatibility_date = "2025-08-23"
type = "javascript"

# -------------------------------
# 生产环境
[env.production]
# route = "https://your-production-domain/*"
# zone_id = "your-production-zone-id"

[[env.production.kv_namespaces]]
binding = "bpb1"            # Worker 内访问 KV 的名字
id = "3eeaf8b9722a469a8f6fe4e019b396bc"  # KV namespace ID，从 UI 获取

# -------------------------------
# 预览环境
[env.preview]
# route = "https://dev.example.com/*"
# zone_id = "your-preview-zone-id"

[[env.preview.kv_namespaces]]
binding = "bpb1"
id = "3eeaf8b9722a469a8f6fe4e019b396bc"
